# Generated by Django 5.0.6 on 2024-06-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="destination",
            new_name="place",
        ),
    ]
