# Generated by Django 5.0.6 on 2024-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_rename_destination_habit_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Укажите является ли данная привычка полезной",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Укажите является ли данная привычка публичной",
                verbose_name="Признак публичности",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                choices=[
                    (1, "Каждый день"),
                    (2, "Каждые два дня"),
                    (3, "Каждые три дня"),
                    (4, "Каждые четыре дня"),
                    (5, "Каждые пять дней"),
                    (6, "Каждые шесть дней"),
                    (7, "Каждую неделю"),
                ],
                default=1,
                help_text="Укажите периодичность привычки",
                verbose_name="Периодичность привычки",
            ),
        ),
    ]
