# Generated by Django 5.0.6 on 2024-06-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_remove_habit_time_of_habit_habit_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="time",
            new_name="time_of_habit",
        ),
    ]
